### ISSUE TITLE
Laravel 8 supported?

### ISSUE THREAD

**Issue by makopov** [barexammasters/laravel-loki-logger#1]
Have you tried this with Laravel 8? I've got it running on mine but I'm seeing this error.

```
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] 
(InvalidArgumentException(code: 0): LokiLogger must be an instance of Monolog\\Handler\\HandlerInterface
```

**Comment by publiux** [comment]
Sort of. I merged changes to make it work with L8 to https://github.com/devcake-deventer/laravel-loki-logging . I would use that instead. It's working fine for my in K8s.
